/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface IValidatorDepositRedeemHostInterface extends Interface {
    getFunction(nameOrSignature: "beneficiaryNonces" | "consumeBeneficiaryNonceForMarket" | "guardianIdBeneficiary" | "transferOneGuardianIdForMarket" | "usdcTokenAddress"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'beneficiaryNonces', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'consumeBeneficiaryNonceForMarket', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'guardianIdBeneficiary', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOneGuardianIdForMarket', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'usdcTokenAddress', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'beneficiaryNonces', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'consumeBeneficiaryNonceForMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'guardianIdBeneficiary', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOneGuardianIdForMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdcTokenAddress', data: BytesLike): Result;
  }

  

  export interface IValidatorDepositRedeemHost extends BaseContract {
    
    connect(runner?: ContractRunner | null): IValidatorDepositRedeemHost;
    waitForDeployment(): Promise<this>;

    interface: IValidatorDepositRedeemHostInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    beneficiaryNonces: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    consumeBeneficiaryNonceForMarket: TypedContractMethod<
      [account: AddressLike, nonce: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    guardianIdBeneficiary: TypedContractMethod<
      [guardianId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    transferOneGuardianIdForMarket: TypedContractMethod<
      [from: AddressLike, to: AddressLike, guardianId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    usdcTokenAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'beneficiaryNonces'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'consumeBeneficiaryNonceForMarket'): TypedContractMethod<
      [account: AddressLike, nonce: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'guardianIdBeneficiary'): TypedContractMethod<
      [guardianId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOneGuardianIdForMarket'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, guardianId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdcTokenAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }