/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface BusinessStartKetInterface extends Interface {
    getFunction(nameOrSignature: "addAdmin" | "adminBurn" | "adminBurnBatch" | "admins" | "balanceOf" | "balanceOfBatch" | "collectionName" | "collectionSymbol" | "isApprovedForAll" | "mint" | "mintBatch" | "removeAdmin" | "safeBatchTransferFrom" | "safeTransferFrom" | "setApprovalForAll" | "setURI" | "supportsInterface" | "uri"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AdminAdded" | "AdminRemoved" | "ApprovalForAll" | "TransferBatch" | "TransferSingle" | "URI"): EventFragment;

    encodeFunctionData(functionFragment: 'addAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'adminBurn', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'adminBurnBatch', values: [AddressLike, BigNumberish[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'admins', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOfBatch', values: [AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'collectionName', values?: undefined): string;
encodeFunctionData(functionFragment: 'collectionSymbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'mint', values: [AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'mintBatch', values: [AddressLike, BigNumberish[], BigNumberish[], BytesLike]): string;
encodeFunctionData(functionFragment: 'removeAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'safeBatchTransferFrom', values: [AddressLike, AddressLike, BigNumberish[], BigNumberish[], BytesLike]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setURI', values: [string]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'uri', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'adminBurn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'adminBurnBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admins', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOfBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'collectionName', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'collectionSymbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeBatchTransferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uri', data: BytesLike): Result;
  }

  
    export namespace AdminAddedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AdminRemovedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalForAllEvent {
      export type InputTuple = [account: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [account: string, operator: string, approved: boolean];
      export interface OutputObject {account: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferBatchEvent {
      export type InputTuple = [operator: AddressLike, from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[]];
      export type OutputTuple = [operator: string, from: string, to: string, ids: bigint[], values: bigint[]];
      export interface OutputObject {operator: string, from: string, to: string, ids: bigint[], values: bigint[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferSingleEvent {
      export type InputTuple = [operator: AddressLike, from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish];
      export type OutputTuple = [operator: string, from: string, to: string, id: bigint, value: bigint];
      export interface OutputObject {operator: string, from: string, to: string, id: bigint, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace URIEvent {
      export type InputTuple = [value: string, id: BigNumberish];
      export type OutputTuple = [value: string, id: bigint];
      export interface OutputObject {value: string, id: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BusinessStartKet extends BaseContract {
    
    connect(runner?: ContractRunner | null): BusinessStartKet;
    waitForDeployment(): Promise<this>;

    interface: BusinessStartKetInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addAdmin: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    adminBurn: TypedContractMethod<
      [from: AddressLike, id: BigNumberish, value: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    adminBurnBatch: TypedContractMethod<
      [from: AddressLike, ids: BigNumberish[], values: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    admins: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, id: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    balanceOfBatch: TypedContractMethod<
      [accounts: AddressLike[], ids: BigNumberish[], ],
      [bigint[]],
      'view'
    >
    

    
    collectionName: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    collectionSymbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [account: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [to: AddressLike, id: BigNumberish, amount: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    mintBatch: TypedContractMethod<
      [to: AddressLike, ids: BigNumberish[], amounts: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    removeAdmin: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    safeBatchTransferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    safeTransferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setURI: TypedContractMethod<
      [newuri: string, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    uri: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addAdmin'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'adminBurn'): TypedContractMethod<
      [from: AddressLike, id: BigNumberish, value: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'adminBurnBatch'): TypedContractMethod<
      [from: AddressLike, ids: BigNumberish[], values: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'admins'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, id: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOfBatch'): TypedContractMethod<
      [accounts: AddressLike[], ids: BigNumberish[], ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'collectionName'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'collectionSymbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [account: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [to: AddressLike, id: BigNumberish, amount: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintBatch'): TypedContractMethod<
      [to: AddressLike, ids: BigNumberish[], amounts: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeAdmin'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeBatchTransferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setURI'): TypedContractMethod<
      [newuri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'uri'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;

    getEvent(key: 'AdminAdded'): TypedContractEvent<AdminAddedEvent.InputTuple, AdminAddedEvent.OutputTuple, AdminAddedEvent.OutputObject>;
getEvent(key: 'AdminRemoved'): TypedContractEvent<AdminRemovedEvent.InputTuple, AdminRemovedEvent.OutputTuple, AdminRemovedEvent.OutputObject>;
getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'TransferBatch'): TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
getEvent(key: 'TransferSingle'): TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
getEvent(key: 'URI'): TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;

    filters: {
      
      'AdminAdded(address)': TypedContractEvent<AdminAddedEvent.InputTuple, AdminAddedEvent.OutputTuple, AdminAddedEvent.OutputObject>;
      AdminAdded: TypedContractEvent<AdminAddedEvent.InputTuple, AdminAddedEvent.OutputTuple, AdminAddedEvent.OutputObject>;
    

      'AdminRemoved(address)': TypedContractEvent<AdminRemovedEvent.InputTuple, AdminRemovedEvent.OutputTuple, AdminRemovedEvent.OutputObject>;
      AdminRemoved: TypedContractEvent<AdminRemovedEvent.InputTuple, AdminRemovedEvent.OutputTuple, AdminRemovedEvent.OutputObject>;
    

      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'TransferBatch(address,address,address,uint256[],uint256[])': TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
      TransferBatch: TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
    

      'TransferSingle(address,address,address,uint256,uint256)': TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
      TransferSingle: TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
    

      'URI(string,uint256)': TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
      URI: TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
    
    };
  }