/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { BeamioUserCardDeployerV07, BeamioUserCardDeployerV07Interface } from "../../BeamioUserCard/BeamioUserCardDeployerV07.js";

  const _abi = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "BM_DeployFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "BM_ZeroAddress",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "DEP_InvalidFactory",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "DEP_NotFactory",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "DEP_NotOwner",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "oldFactory",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "newFactory",
        "type": "address"
      }
    ],
    "name": "FactoryChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "oldOwner",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "OwnerChanged",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "initCode",
        "type": "bytes"
      }
    ],
    "name": "deploy",
    "outputs": [
      {
        "internalType": "address",
        "name": "addr",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "factory",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "f",
        "type": "address"
      }
    ],
    "name": "setFactory",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "transferOwner",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608080604052346026575f80546001600160a01b03191633179055610308908161002b8239f35b5f80fdfe60806040526004361015610011575f80fd5b5f3560e01c8062774360146100635780634fb2e45d1461005e5780635bb47808146100595780638da5cb5b146100545763c45a01551461004f575f80fd5b610245565b61021e565b61018a565b610104565b346100de5760203660031901126100de576004356001600160401b0381116100de57366023820112156100de576004810135906001600160401b0382116100de5736602483830101116100de576100da9160246100c0920161026d565b6040516001600160a01b0390911681529081906020820190565b0390f35b5f80fd5b60209060031901126100de576004356001600160a01b03811681036100de5790565b346100de57610112366100e2565b5f546001600160a01b038116913383900361017b576001600160a01b031691821561016c5782907fb532073b38c83145e3e5135377a08bf9aab55bc0fd7c1179cd4fb995d2a5159c5f80a36001600160a01b031916175f55005b63a9b8048960e01b5f5260045ffd5b6325b74aa560e21b5f5260045ffd5b346100de57610198366100e2565b5f546001600160a01b0316330361017b576001600160a01b038116908115908115610214575b5061020557600154816001600160a01b0382167ff36cf3b7f3187ed5217f19ea5137ed68a98983b4d678c78eb886fc378d2c13cf5f80a36001600160a01b03191617600155005b639519c0cd60e01b5f5260045ffd5b90503b155f6101be565b346100de575f3660031901126100de575f546040516001600160a01b039091168152602090f35b346100de575f3660031901126100de576001546040516001600160a01b039091168152602090f35b6001549091906001600160a01b0316330361028e5761028b9161029d565b90565b63226e43bf60e21b5f5260045ffd5b81156102c357816040519182375ff0906001600160a01b038216156102be57565b5f9150565b633448691b60e11b5f5260045ffdfea2646970667358221220643e0886c95e72dd345d30629e8d00b8ddcbf33a95afa38e2e52134c94e53c0464736f6c63430008210033";

  
      type BeamioUserCardDeployerV07ConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: BeamioUserCardDeployerV07ConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class BeamioUserCardDeployerV07__factory extends ContractFactory {
    
      constructor(...args: BeamioUserCardDeployerV07ConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<BeamioUserCardDeployerV07 & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): BeamioUserCardDeployerV07__factory {
      return super.connect(runner) as BeamioUserCardDeployerV07__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): BeamioUserCardDeployerV07Interface {
      return new Interface(_abi) as BeamioUserCardDeployerV07Interface;
    }
    
    override attach(address: string | Addressable): BeamioUserCardDeployerV07 {
      return super.attach(address) as BeamioUserCardDeployerV07;
    }
  static connect(address: string, runner?: ContractRunner | null): BeamioUserCardDeployerV07 {
      return new Contract(address, _abi, runner) as unknown as BeamioUserCardDeployerV07;
    }
  }

  
  