/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface IGBTokenErc20BridgeInterface extends Interface {
    getFunction(nameOrSignature: "bridgeableBalanceOf" | "burnPaidFrom" | "mintPaid"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'bridgeableBalanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'burnPaidFrom', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'mintPaid', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'bridgeableBalanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burnPaidFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintPaid', data: BytesLike): Result;
  }

  

  export interface IGBTokenErc20Bridge extends BaseContract {
    
    connect(runner?: ContractRunner | null): IGBTokenErc20Bridge;
    waitForDeployment(): Promise<this>;

    interface: IGBTokenErc20BridgeInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    bridgeableBalanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    burnPaidFrom: TypedContractMethod<
      [account: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    mintPaid: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'bridgeableBalanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'burnPaidFrom'): TypedContractMethod<
      [account: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintPaid'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }