/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface MembershipFeeOpsLibInterface extends Interface {
    getFunction(nameOrSignature: "membershipFeeMode" | "membershipFees" | "requireGatewayOrPaymaster" | "requireOwnerOrGateway" | "resolveAcct"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MembershipFeePurchaseCleared" | "MembershipFeePurchaseStaged" | "MembershipFeesUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'membershipFeeMode', values?: undefined): string;
encodeFunctionData(functionFragment: 'membershipFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'requireGatewayOrPaymaster', values?: undefined): string;
encodeFunctionData(functionFragment: 'requireOwnerOrGateway', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveAcct', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'membershipFeeMode', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'membershipFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requireGatewayOrPaymaster', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requireOwnerOrGateway', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveAcct', data: BytesLike): Result;
  }

  
    export namespace MembershipFeePurchaseClearedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MembershipFeePurchaseStagedEvent {
      export type InputTuple = [account: AddressLike, tierIndex: BigNumberish, feePaid6: BigNumberish, pointsCredit6: BigNumberish, deadline: BigNumberish];
      export type OutputTuple = [account: string, tierIndex: bigint, feePaid6: bigint, pointsCredit6: bigint, deadline: bigint];
      export interface OutputObject {account: string, tierIndex: bigint, feePaid6: bigint, pointsCredit6: bigint, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MembershipFeesUpdatedEvent {
      export type InputTuple = [tierCount: BigNumberish];
      export type OutputTuple = [tierCount: bigint];
      export interface OutputObject {tierCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MembershipFeeOpsLib extends BaseContract {
    
    connect(runner?: ContractRunner | null): MembershipFeeOpsLib;
    waitForDeployment(): Promise<this>;

    interface: MembershipFeeOpsLibInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    membershipFeeMode: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    membershipFees: TypedContractMethod<
      [],
      [[bigint[], bigint[]] & {feeE6: bigint[], durationKind: bigint[] }],
      'view'
    >
    

    
    requireGatewayOrPaymaster: TypedContractMethod<
      [],
      [void],
      'view'
    >
    

    
    requireOwnerOrGateway: TypedContractMethod<
      [],
      [void],
      'view'
    >
    

    
    resolveAcct: TypedContractMethod<
      [user: AddressLike, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'membershipFeeMode'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'membershipFees'): TypedContractMethod<
      [],
      [[bigint[], bigint[]] & {feeE6: bigint[], durationKind: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'requireGatewayOrPaymaster'): TypedContractMethod<
      [],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'requireOwnerOrGateway'): TypedContractMethod<
      [],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'resolveAcct'): TypedContractMethod<
      [user: AddressLike, ],
      [string],
      'view'
    >;

    getEvent(key: 'MembershipFeePurchaseCleared'): TypedContractEvent<MembershipFeePurchaseClearedEvent.InputTuple, MembershipFeePurchaseClearedEvent.OutputTuple, MembershipFeePurchaseClearedEvent.OutputObject>;
getEvent(key: 'MembershipFeePurchaseStaged'): TypedContractEvent<MembershipFeePurchaseStagedEvent.InputTuple, MembershipFeePurchaseStagedEvent.OutputTuple, MembershipFeePurchaseStagedEvent.OutputObject>;
getEvent(key: 'MembershipFeesUpdated'): TypedContractEvent<MembershipFeesUpdatedEvent.InputTuple, MembershipFeesUpdatedEvent.OutputTuple, MembershipFeesUpdatedEvent.OutputObject>;

    filters: {
      
      'MembershipFeePurchaseCleared(address)': TypedContractEvent<MembershipFeePurchaseClearedEvent.InputTuple, MembershipFeePurchaseClearedEvent.OutputTuple, MembershipFeePurchaseClearedEvent.OutputObject>;
      MembershipFeePurchaseCleared: TypedContractEvent<MembershipFeePurchaseClearedEvent.InputTuple, MembershipFeePurchaseClearedEvent.OutputTuple, MembershipFeePurchaseClearedEvent.OutputObject>;
    

      'MembershipFeePurchaseStaged(address,uint256,uint256,uint256,uint64)': TypedContractEvent<MembershipFeePurchaseStagedEvent.InputTuple, MembershipFeePurchaseStagedEvent.OutputTuple, MembershipFeePurchaseStagedEvent.OutputObject>;
      MembershipFeePurchaseStaged: TypedContractEvent<MembershipFeePurchaseStagedEvent.InputTuple, MembershipFeePurchaseStagedEvent.OutputTuple, MembershipFeePurchaseStagedEvent.OutputObject>;
    

      'MembershipFeesUpdated(uint256)': TypedContractEvent<MembershipFeesUpdatedEvent.InputTuple, MembershipFeesUpdatedEvent.OutputTuple, MembershipFeesUpdatedEvent.OutputObject>;
      MembershipFeesUpdated: TypedContractEvent<MembershipFeesUpdatedEvent.InputTuple, MembershipFeesUpdatedEvent.OutputTuple, MembershipFeesUpdatedEvent.OutputObject>;
    
    };
  }