/** @type {import('tailwindcss').Config} */
export default {
	content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
	darkMode: 'class',
	theme: {
		extend: {
			colors: {
				'surface-tint': '#0054d8',
				'surface-bright': '#f9f9fe',
				'on-secondary-container': '#344a86',
				'on-tertiary': '#ffffff',
				'on-secondary-fixed-variant': '#2e447f',
				'primary-fixed': '#dbe1ff',
				'secondary-fixed-dim': '#b3c5ff',
				'outline-variant': '#c3c6d8',
				'tertiary-fixed-dim': '#ffb59a',
				'on-surface': '#1a1c1f',
				'on-primary-fixed-variant': '#003fa5',
				surface: '#f9f9fe',
				'on-secondary-fixed': '#00184a',
				error: '#ba1a1a',
				'on-background': '#1a1c1f',
				'tertiary-fixed': '#ffdbce',
				'surface-container-low': '#f3f3f8',
				background: '#f9f9fe',
				'secondary-container': '#a7bcff',
				'primary-container': '#1562f0',
				'on-error-container': '#93000a',
				'inverse-surface': '#2e3034',
				'on-tertiary-container': '#ffece6',
				tertiary: '#973300',
				secondary: '#465c99',
				'surface-variant': '#e2e2e7',
				'surface-container-highest': '#e2e2e7',
				'primary-fixed-dim': '#b3c5ff',
				'tertiary-container': '#c04300',
				'on-secondary': '#ffffff',
				outline: '#737687',
				'on-primary-fixed': '#00184a',
				'on-tertiary-fixed-variant': '#802a00',
				'surface-container-lowest': '#ffffff',
				'inverse-on-surface': '#f0f0f5',
				'surface-container': '#ededf2',
				'surface-container-high': '#e8e8ed',
				'on-primary-container': '#edefff',
				'on-error': '#ffffff',
				'on-primary': '#ffffff',
				'secondary-fixed': '#dbe1ff',
				primary: '#004bc3',
				'error-container': '#ffdad6',
				'on-surface-variant': '#424655',
				'inverse-primary': '#b3c5ff',
				'on-tertiary-fixed': '#370d00',
				'surface-dim': '#d9dade',
			},
			fontFamily: {
				headline: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
				body: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
				label: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
			},
			borderRadius: {
				DEFAULT: '1rem',
				lg: '2rem',
				xl: '3rem',
				full: '9999px',
			},
		},
	},
	plugins: [],
}
