/** @type {import('tailwindcss').Config} */
export default {
	content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
	darkMode: 'class',
	theme: {
		extend: {
			colors: {
				'on-surface-variant': '#595c5e',
				'tertiary-dim': '#7f2d7e',
				'primary-fixed': '#7a9dff',
				'tertiary-container': '#f797ef',
				'on-primary': '#f1f2ff',
				'inverse-surface': '#0b0f10',
				'surface-dim': '#d0d5d8',
				'outline-variant': '#abadaf',
				'on-tertiary': '#ffeef8',
				'primary-dim': '#0047b8',
				'on-secondary-fixed-variant': '#515c70',
				'surface-bright': '#f5f7f9',
				'secondary-container': '#d8e3fb',
				'on-tertiary-container': '#610e62',
				'on-surface': '#2c2f31',
				background: '#f5f7f9',
				primary: '#0051d1',
				'tertiary-fixed-dim': '#e88ae1',
				'surface-container-highest': '#d9dde0',
				tertiary: '#8d3a8b',
				'surface-variant': '#d9dde0',
				'on-primary-fixed': '#000000',
				'on-primary-fixed-variant': '#00276d',
				'inverse-on-surface': '#9a9d9f',
				'on-secondary': '#eff2ff',
				'tertiary-fixed': '#f797ef',
				'surface-container': '#e5e9eb',
				'on-background': '#2c2f31',
				'inverse-primary': '#5f8bff',
				'surface-container-lowest': '#ffffff',
				surface: '#f5f7f9',
				'surface-tint': '#0051d1',
				'on-secondary-container': '#475266',
				'error-container': '#fb5151',
				'surface-container-high': '#dfe3e6',
				'on-secondary-fixed': '#354053',
				secondary: '#515c70',
				'secondary-fixed-dim': '#cad5ed',
				'on-primary-container': '#001e59',
				error: '#b31b25',
				'on-tertiary-fixed': '#400041',
				'error-dim': '#9f0519',
				'secondary-fixed': '#d8e3fb',
				'primary-fixed-dim': '#648eff',
				'on-tertiary-fixed-variant': '#6c1a6c',
				'surface-container-low': '#eef1f3',
				'secondary-dim': '#455064',
				outline: '#747779',
				'primary-container': '#7a9dff',
				'on-error-container': '#570008',
				'on-error': '#ffefee',
			},
			fontFamily: {
				headline: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
				body: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
				label: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
			},
			borderRadius: {
				DEFAULT: '1rem',
				lg: '2rem',
				xl: '3rem',
				full: '9999px',
			},
		},
	},
	plugins: [],
}
