/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface IGBTokenSettlementInterface extends Interface {
    getFunction(nameOrSignature: "balanceOfAll" | "consumeGb" | "mintPaid"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'balanceOfAll', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'consumeGb', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'mintPaid', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'balanceOfAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'consumeGb', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintPaid', data: BytesLike): Result;
  }

  

  export interface IGBTokenSettlement extends BaseContract {
    
    connect(runner?: ContractRunner | null): IGBTokenSettlement;
    waitForDeployment(): Promise<this>;

    interface: IGBTokenSettlementInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    balanceOfAll: TypedContractMethod<
      [account: AddressLike, ],
      [[bigint, bigint, bigint] & {total: bigint, free: bigint, paid: bigint }],
      'view'
    >
    

    
    consumeGb: TypedContractMethod<
      [user: AddressLike, amount: BigNumberish, ],
      [[bigint, bigint] & {freeBurned: bigint, paidBurned: bigint }],
      'nonpayable'
    >
    

    
    mintPaid: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'balanceOfAll'): TypedContractMethod<
      [account: AddressLike, ],
      [[bigint, bigint, bigint] & {total: bigint, free: bigint, paid: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'consumeGb'): TypedContractMethod<
      [user: AddressLike, amount: BigNumberish, ],
      [[bigint, bigint] & {freeBurned: bigint, paidBurned: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintPaid'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }