/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IBeamioAccountFactoryResolve, IBeamioAccountFactoryResolveInterface } from "../../../BeamioUserCard/AdminStatsQueryModuleV3.sol/IBeamioAccountFactoryResolve.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "eoa",
        "type": "address"
      }
    ],
    "name": "beamioAccountOf",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IBeamioAccountFactoryResolve__factory {
    static readonly abi = _abi;
    static createInterface(): IBeamioAccountFactoryResolveInterface {
      return new Interface(_abi) as IBeamioAccountFactoryResolveInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IBeamioAccountFactoryResolve {
      return new Contract(address, _abi, runner) as unknown as IBeamioAccountFactoryResolve;
    }
  }
  